spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db?currentSchema=main
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  cloud:
    aws:
      stack:
        name: localstack
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566

logging:
  level:
    com.adriano.sqsxmlmessaging: DEBUG
    org.springframework: INFO
